modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0-only"
[[mods]]
modId="lazoboombox"
version="0.1.0+mc1.21.11"
displayName="LazoBoombox"
displayTest="IGNORE_ALL_VERSION"
logoFile="icon.png"
authors="EyeCrasher"
description="Portable + placeable Boombox addon for LazoDiscs."
[[dependencies.lazoboombox]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.lazoboombox]]
modId="minecraft"
type="required"
versionRange="[1.21.11,)"
ordering="NONE"
side="BOTH"
[[dependencies.lazoboombox]]
modId="plasmovoice"
type="required"
versionRange="[2.1.8,)"
ordering="NONE"
side="BOTH"
[[dependencies.lazoboombox]]
modId="lazodiscs"
type="required"
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
